import { MoveRegistry, type Move } from "../../domain/move";

const MOVES: Move[] = [
  {
    id: "volt_tackle",
    name: "Volt Tackle",
    type: "electric",
    category: "physical",
    power: 80,
    accuracy: 95,
    effects: [
      { kind: "status", target: "foe", status: "paralyzed", chance: 0.2 },
    ],
    description: "A reckless electric charge.",
    scope: "signature",
    signatureFor: "hoppy",
  },
  {
    id: "lions_roar",
    name: "Lion's Roar",
    type: "fire",
    category: "physical",
    power: 75,
    accuracy: 100,
    effects: [{ kind: "stage", target: "foe", stat: "atk", delta: -1 }],
    description: "A blazing roar that cows the foe.",
    scope: "signature",
    signatureFor: "emberlea",
  },
  {
    id: "blizzard_breath",
    name: "Blizzard Breath",
    type: "ice",
    category: "focus",
    power: 80,
    accuracy: 90,
    effects: [{ kind: "status", target: "foe", status: "freeze", chance: 0.2 }],
    description: "An icy gust that may freeze.",
    scope: "signature",
    signatureFor: "frostpaw",
  },
  {
    id: "stretch_punch",
    name: "Stretch Punch",
    type: "normal",
    category: "physical",
    power: 80,
    accuracy: 100,
    effects: [],
    description: "An impossibly long arm strike.",
    scope: "signature",
    signatureFor: "stretch",
  },
  {
    id: "lullaby",
    name: "Lullaby",
    type: "flying",
    category: "status",
    power: 0,
    accuracy: 75,
    effects: [{ kind: "status", target: "foe", status: "asleep", chance: 1 }],
    description: "A song that puts the foe to sleep.",
    scope: "signature",
    signatureFor: "chatter",
  },
  {
    id: "bubble_barrage",
    name: "Bubble Barrage",
    type: "aqua",
    category: "focus",
    power: 80,
    accuracy: 100,
    effects: [
      { kind: "stage", target: "foe", stat: "spd", delta: -1, chance: 0.3 },
    ],
    description: "A flurry of bubbles that may slow.",
    scope: "signature",
    signatureFor: "aquack",
  },
  {
    id: "sky_dive",
    name: "Sky Dive",
    type: "flying",
    category: "physical",
    power: 85,
    accuracy: 95,
    effects: [],
    description: "A plummeting raptor strike.",
    scope: "signature",
    signatureFor: "talon",
  },
  {
    id: "mind_break",
    name: "Mind Break",
    type: "psychic",
    category: "focus",
    power: 85,
    accuracy: 100,
    effects: [
      { kind: "stage", target: "foe", stat: "foc", delta: -1, chance: 0.3 },
    ],
    description: "Tears at the foe's psyche.",
    scope: "signature",
    signatureFor: "hoots",
  },
  {
    id: "chomp",
    name: "Chomp",
    type: "plant",
    category: "physical",
    power: 80,
    accuracy: 100,
    effects: [],
    description: "A vicious munch.",
    scope: "signature",
    signatureFor: "nibble",
  },
  {
    id: "bloom_burst",
    name: "Bloom Burst",
    type: "plant",
    category: "focus",
    power: 80,
    accuracy: 100,
    effects: [{ kind: "heal", target: "self", pct: 0.1 }],
    description: "A petal explosion that heals the user.",
    scope: "signature",
    signatureFor: "sprig",
  },
];

for (const m of MOVES) MoveRegistry.register(m);
