import { MoveRegistry, type Move } from "../../domain/move";

const MOVES: Move[] = [
  {
    id: "tackle",
    name: "Tackle",
    type: "normal",
    category: "physical",
    power: 35,
    accuracy: 100,
    effects: [],
    description: "A full-body charge.",
    scope: "universal",
  },
  {
    id: "growl",
    name: "Growl",
    type: "normal",
    category: "status",
    power: 0,
    accuracy: 100,
    effects: [{ kind: "stage", target: "foe", stat: "atk", delta: -1 }],
    description: "Lowers the foe's Attack.",
    scope: "universal",
  },
  {
    id: "tail_whip",
    name: "Tail Whip",
    type: "normal",
    category: "status",
    power: 0,
    accuracy: 100,
    effects: [{ kind: "stage", target: "foe", stat: "def", delta: -1 }],
    description: "Lowers the foe's Defense.",
    scope: "universal",
  },
  {
    id: "quick_attack",
    name: "Quick Attack",
    type: "normal",
    category: "physical",
    power: 30,
    accuracy: 100,
    effects: [{ kind: "priority", bonus: 1 }],
    description: "Always strikes first.",
    scope: "universal",
  },
  {
    id: "headbutt",
    name: "Headbutt",
    type: "normal",
    category: "physical",
    power: 70,
    accuracy: 100,
    effects: [],
    description: "A heavy headfirst slam.",
    scope: "universal",
  },
  {
    id: "focus_up",
    name: "Focus Up",
    type: "normal",
    category: "status",
    power: 0,
    accuracy: 100,
    effects: [{ kind: "stage", target: "self", stat: "foc", delta: 1 }],
    description: "Sharpens the user's Focus.",
    scope: "universal",
  },
  {
    id: "rest",
    name: "Rest",
    type: "normal",
    category: "status",
    power: 0,
    accuracy: 100,
    effects: [{ kind: "rest" }],
    description: "Fully heals; user falls asleep for 2 turns.",
    scope: "universal",
  },
];

for (const m of MOVES) MoveRegistry.register(m);
